<?php include("header.php");?></div>
</header>
<main>
	<section class="page-header clearfix">
		<div class="container"><br>
			<div class="page-title">
				<h1>Términos y Condiciones de Amination</h1>
				<h2 class="sub-title">Estos son los términos y condiciones de nuestro servicio, todo usuario los acepta al registrarse o jugar en nuestro servidor.</h2>
			</div>
		</div>
	</section>
	
	<section class="page-content staff-content container clearfix">

<br><br><br><br>
	

<p class="bold" id="Licencia" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Licencia</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Al acceder a este sitio web, usted est&aacute; aceptando que quedar&aacute; vinculado a estos T&eacute;rminos y Condiciones de Uso, todas las leyes y reglamentos aplicables y acepta que es responsable del cumplimiento de las leyes locales aplicables. Si usted no est&aacute; de acuerdo con cualquiera de estos t&eacute;rminos, est&aacute; prohibido el uso o acceso a este sitio. Los materiales y contenidos utilizados en este sitio y en el juego, est&aacute;n bajo la siguiente licencia:</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111);  text-align: center;"><a href="http://creativecommons.org/licenses/by-nc-nd/4.0/" original-title="" rel="license" style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; text-decoration-line: none; color: dodgerblue; font-size: 16px;"><img alt="Licencia Creative Commons" original-title="" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" style="margin: 0px; padding: 0px; border: 0px solid; outline: 0px; max-width: 100%;" /></a></p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111);  text-align: center;"><br style="margin: 0px; padding: 0px;" />
Amination se distribuye bajo una&nbsp;<a href="http://creativecommons.org/licenses/by-nc-nd/4.0/" original-title="" rel="license" style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; text-decoration-line: none; color: dodgerblue; font-size: 16px;">Licencia Creative Commons Atribuci&oacute;n-NoComercial-SinDerivar 4.0 Internacional</a>.<br style="margin: 0px; padding: 0px;" />
&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111);  text-align: center;">&nbsp;</p>
<p class="bold" id="UsoDeLicencia" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Uso de Licencia</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Se concede permiso para descargar temporalmente una copia de los materiales (informaci&oacute;n/software) en el sitio web de Amination para visualizaci&oacute;n transitoria personal, no comercial. Esta es una concesi&oacute;n de licencia y no la transferencia de la misma, bajo esta licencia no se podr&aacute;:</p>
<ul style="margin-top: 0px; margin-bottom: 0px; padding-right: 0px; padding-left: 1em; border: 0px none; outline: 0px; list-style-position: inside; line-height: 20.3px; color: rgb(111, 111, 111); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify; ">
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Modificar o copiar material.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Usar los materiales para cualquier prop&oacute;sito comercial o para cualquier exhibici&oacute;n p&uacute;blica (comercial o no comercial).</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Intentar des-encriptar, realizar ingenier&iacute;a inversa y dem&aacute;s a cualquier software/contenido publicado en el sitio web de Amination.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Eliminar cualquier derecho de autor u otras anotaciones de propiedad en los materiales.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Transferir el material obtenido de la web de Amination o subir el material a otro servidor para ser descargado por otros u cualquier otro fin.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Esta licencia expirar&aacute; autom&aacute;ticamente si usted viola cualquiera de estas restricciones y puede ser denunciado por Amination en cualquier momento. Al terminar su visi&oacute;n de los materiales o al t&eacute;rmino de esta licencia, deber&aacute; destruir cualquier material descargado en su poder, ya sea en formato electr&oacute;nico o impreso.</li>
</ul>
<p class="bold" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="MargasRegistradas" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Marcas registradas y Copyrights</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los contenidos y materiales de Minecraft son marcas comerciales y derechos de autor de&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">Mojang AB</strong>&nbsp;o sus licencias. Todos los derechos reservados. Este sitio web forma parte de Amination Network y no est&aacute; afiliado a&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">Mojang AB</strong></p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="PoliticaPrivacidad" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Pol&iacute;tica de Privacidad</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Amination no compartir&aacute; ning&uacute;n dato personal con los visitantes de la web. Los datos personales son necesarios de enviar cuando se rellena alg&uacute;n formulario o utilizando cualquier tipo de forma para realizar el pedido a trav&eacute;s de Amination . De acuerdo a la Ley 09-08, tiene derecho a acceder, modificar o rechazar cualquier procesamiento de sus datos personales. Este proceso est&aacute; autorizado por la CNDP con el n&ordm; de autorizaci&oacute;n D-TH-86/2016 de 02/08/2016.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">DECLARACI&Oacute;N GENERAL DE PRINCIPIOS</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Como se describe en detalle m&aacute;s adelante, cualquier informaci&oacute;n que recolectemos en este sitio web es estrictamente para nuestro uso y no es compartida con ninguna otra entidad, p&uacute;blica o privada, bajo ning&uacute;n concepto. As&iacute; como tampoco se destribuir&aacute; su informaci&oacute;n para campa&ntilde;as de otras entidades ni casos similares.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Su privacidad es muy importante para nosotros. En consecuencia de ello, hemos desarrollado esta pol&iacute;tica para que usted pueda entender c&oacute;mo recopilamos, utilizamos, comunicamos, divulgamos y hacer uso de la informaci&oacute;n personal. A continuaci&oacute;n se describe nuestra pol&iacute;tica de privacidad.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<ul style="margin-top: 0px; margin-bottom: 0px; padding-right: 0px; padding-left: 1em; border: 0px none; outline: 0px; list-style-position: inside; line-height: 20.3px; color: rgb(111, 111, 111); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify; ">
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Antes o en el momento de la recogida de informaci&oacute;n personal, identificaremos los fines para los que se est&aacute; siendo recopilada.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Vamos a recoger y usar la informaci&oacute;n personal con el &uacute;nico objetivo de cumplir los fines especificados por nosotros y para otros fines compatibles, a menos que obtengamos el consentimiento de la persona interesada o como lo requiere la ley de protecci&oacute;n de datos.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">S&oacute;lo se conservar&aacute;n los datos personales durante el tiempo necesario para el cumplimiento de dichos fines.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Nosotros recogemos informaci&oacute;n personal por medios leg&iacute;timos y justos y, en su caso, con el conocimiento o consentimiento de la persona afectada.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Los datos personales deben ser pertinentes a los fines para los que se va a utilizar, y, en la medida necesaria para esos fines, debe ser precisa, completa y actualizada.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Vamos a proteger la informaci&oacute;n personal de forma razonable contra p&eacute;rdida o robo, as&iacute; como el acceso no autorizado, divulgaci&oacute;n, copia, uso o modificaci&oacute;n.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Vamos a poner a disposici&oacute;n de los clientes informaci&oacute;n acerca de nuestras pol&iacute;ticas y pr&aacute;cticas relacionadas con la gesti&oacute;n de la informaci&oacute;n personal.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Estamos comprometidos a llevar a cabo nuestro negocio de acuerdo con estos principios con el fin de asegurar la confidencialidad de la informaci&oacute;n personal est&aacute; protegida y mantenida.</li>
</ul>
<p style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">&nbsp;</p>
<p class="bold" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">CORRECCI&Oacute;N/MODIFICACI&Oacute;N/ELIMINACI&Oacute;N DE INFORMACI&Oacute;N</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Si desea corregir, actualizar o eliminar cualquier informaci&oacute;n sobre usted que podamos tener en nuestros registros, por favor, env&iacute;e un correo electr&oacute;nico a soporte@amination.es con los detalles de su solicitud.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="CondicionesGenerales" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Condiciones Generales</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">La utilizaci&oacute;n de esta web supone la aceptaci&oacute;n plena por parte del usuario de todas las condiciones de uso vigentes por lo que rogamos que las lea atentamente y en caso de no estar de acuerdo con su contenido se abstenga de hacer uso de la misma.<br style="margin: 0px; padding: 0px;" />
El cliente se compromete a hacer un uso adecuado del contenido de la web y de los servicios que contrate. Esta obligaci&oacute;n supone el no emplear dichos servicios y contenidos de forma contraria a la legislaci&oacute;n que resulte de aplicaci&oacute;n, ni a utilizarlos para actividades il&iacute;citas, contrarias a la buena fe o al orden p&uacute;blico.<br style="margin: 0px; padding: 0px;" />
Amination Network se reserva el derecho de negar o rechazar la entrada a cualquier nombre de usuario utilizado por cualquier motivo siempre y cuando sea justificado. Si el cliente se registra en el sitio web www.amination.es o www.amination.es a trav&eacute;s del siguiente enlace (https://www.amination.es/foro/index.php?app=core&amp;module=global&amp;section=register) est&aacute; aceptando los T&eacute;rminos y Condiciones para poder seguir navegando. Si el cliente est&aacute; de acuerdo con el contenido de estos t&eacute;rminos legales y del contrato general, deber&aacute; hacer clic sobre el bot&oacute;n&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">&quot;Estoy de acuerdo con los t&eacute;rminos &amp; condiciones de de esta compra.&quot;</strong>&nbsp;para poder comprar cualquier producto de la tienda de Amination Network (https://amination.es). En caso contrario, no podr&aacute; continuar con el proceso de compra o prestaci&oacute;n de servicios.<br style="margin: 0px; padding: 0px;" />
<br style="margin: 0px; padding: 0px;" />
Estas cl&aacute;usulas pueden verse modificadas, tanto en sus actuales t&eacute;rminos legales y contrato general, al objeto de mantenerlos actualizados de acuerdo con la normativa en vigor, por lo que es aconsejable que sean le&iacute;dos en cada visita/contrataci&oacute;n en la p&aacute;gina web&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">www.amination.es</strong>. Estas modificaciones ser&aacute;n aplicables a partir de su publicaci&oacute;n en Internet.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="ModificacionTyC" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Modificaci&oacute;n de los T&eacute;rminos y Condiciones</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Nos reservamos el derecho de cambiar dichos t&eacute;rminos y condiciones cuando sea necesario sin previo aviso. El uso continuado de este sitio web y del juego Amination Network, constituye al reconocimiento y acuerdo de dichos t&eacute;rminos y condiciones modificados. Es responsabilidad del usuario revisar peri&oacute;dicamente este acuerdo para tener constancia en todo momento de las modificaciones.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="HacerPedido" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Hacer un pedido</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los pedidos se realizan exclusivamente online, a trav&eacute;s de la tienda de Amination&nbsp; (http://donar.amination.es) (24h/365d&iacute;as).<br style="margin: 0px; padding: 0px;" />
En cada pedido implica rellenar un formulario, en el que se le solicitan los datos comunes para una correcta facturaci&oacute;n.<br style="margin: 0px; padding: 0px;" />
El cliente declara ser mayor de edad para poder iniciar un pedido y/o el registro como tal. La contrataci&oacute;n llevada a cabo por menores de edad requiere la autorizaci&oacute;n previa de sus padres, tutores o representantes legales, los cuales ser&aacute;n considerados responsables de la contrataci&oacute;n llevada a cabo por los menores a su cargo.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="Precios" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Precios</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los precios de venta indicados en&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">www.amination.es</strong>&nbsp;se muestran en euros.<br style="margin: 0px; padding: 0px;" />
<b>Amination&nbsp;</b>se reserva el derecho de variar las caracter&iacute;sticas y precios de cada servicio, notific&aacute;ndolo previamente en la web en la secci&oacute;n &quot;Noticias &amp; Anuncios&quot;.<br style="margin: 0px; padding: 0px;" />
Le informamos que en caso de que aparezca un precio manifiestamente irrisorio y sea cual sea el motivo&nbsp;<i original-title="" style="margin: 0px; padding: 0px;">(bug inform&aacute;tico, error manual, t&eacute;cnico&hellip;)</i>, el pedido ser&aacute; anulado incluso en caso de validaci&oacute;n inicial.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="MetodosDePago" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">M&eacute;todos de Pago y Disponibilidad</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los m&eacute;todos de pagos disponibles en Amination Network son:</p>
<ul style="margin-top: 0px; margin-bottom: 0px; padding-right: 0px; padding-left: 1em; border: 0px none; outline: 0px; list-style-position: inside; line-height: 20.3px; color: rgb(111, 111, 111); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify; ">
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;"><strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">PayPal</strong>: pago con saldo de cuenta PayPal, con tarjet&aacute; de cr&eacute;dito/d&eacute;bito o con cuenta bancaria.</li>
</ul>
<p style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Todos los art&iacute;culos se entregan de forma inmediata, si hubiese alg&uacute;n retraso con la enterga de cualquier art&iacute;culo adquirido en la tienda de Amination (http://donar.amination.es) se deber&aacute; contactar con el Dept. de Soporte haciendo click aqu&iacute; (https://www.amination.es/foro/index.php?app=forums&amp;module=post&amp;section=post&amp;do=new_post&amp;f=29).</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="LeyDeGobierno" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Ley de Gobierno</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Las presentes Condiciones Generales de Uso, as&iacute; como el uso del Sitio Web, se regir&aacute;n por la legislaci&oacute;n Espa&ntilde;ola. Las partes se someten para la resoluci&oacute;n de los conflictos, y con renuncia a cualquier otro fuero, a los juzgados y tribunales espa&ntilde;oles que resulten competentes de conformidad con la legislaci&oacute;n procesal vigente.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Las reclamaciones que puedan presentar los clientes que ostenten la condici&oacute;n de consumidores en los t&eacute;rminos de la legislaci&oacute;n vigente, ser&aacute;n tratadas por el servicio de atenci&oacute;n al cliente de Amination y ser&aacute;n respondidas por el medio adecuado en el plazo m&aacute;ximo de 30 d&iacute;as.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="RevisionesyErratas" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Revisiones y Erratas</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los materiales que se pueden apreciar en la web de Amination pueden contener errores ortogr&aacute;ficos o en las fotograf&iacute;as. Amination no garantiza que cualquiera de los dos materiales sean precisos, completa o actual. Amination puede hacer cambios a los materiales y contenidos que se aprecian en la web en cualquier momento sin previo aviso. Amination sin embargo, se compromete a actualizar los materiales siempre que sea posible.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="EnlacesLinks" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Enlaces / Links</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Amination no ha revisado todos los v&iacute;nculos que puede haber en la web y los v&iacute;nculos que hay hacia Amination, no es responsable de los contenidos de dichos sitios. La inclusi&oacute;n de estos v&iacute;nculos no implica aprobaci&oacute;n por parte de Amination. El uso de cualquier enlace es bajo el propio riesgo del usuario.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="AccionesProhibidas" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Acciones prohibidas</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Al utilizar cualquiera de los servicios de Amination no podr&aacute;:</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<ul style="margin-top: 0px; margin-bottom: 0px; padding-right: 0px; padding-left: 1em; border: 0px none; outline: 0px; list-style-position: inside; line-height: 20.3px; color: rgb(111, 111, 111); font-family: &quot;Open Sans&quot;, sans-serif; text-align: justify; ">
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Intento de recabar informaci&oacute;n de otros usuarios, a menos que sean notificados.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Publicar cualquier contenido pornogr&aacute;fico, esto incluye enlaces, sitios, im&aacute;genes y dem&aacute;s contenido en relaci&oacute;n a la pornograf&iacute;a.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Subir contenido malicioso o que contenga virus, troyanos y dem&aacute;s elementos que perjudiquen a los usuarios de&nbsp;<span style="font-size: 15px;">Amination</span>.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Hacer bullying, acosar o intimidar a cualquier usuario.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Participar en actividades ilegales. Los usuarios tendr&aacute;n que cumplir con las leyes de Espa&ntilde;a.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Discriminar a otros usuarios y/o publicaciones de los mismos.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">Alterar comunicaciones, consulte &quot;Alteraci&oacute;n de Comunicaciones&quot;.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">La realizaci&oacute;n de una denuncia a un usuario en el foro utilizando pruebas modificadas o con objetivo de lograr sancionar a un jugador sin que este verdaderamente lo haya realizado.</li>
<li style="margin: 0px; padding: 0px; border: 0px none; outline: 0px; font-family: &quot;Open Sans&quot;; line-height: 21px;">El acceso no autorizado a una cuenta de otro jugador en el servidor sin consentimiento de este, en relaci&oacute;n a robo de cuentas y similar.</li>
</ul>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Se recomienda no compartir informaci&oacute;n personal con otros miembros, ya sea correo electr&oacute;nico, redes sociales, n&uacute;mero de tel&eacute;fono y dem&aacute;s v&iacute;as.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Est&aacute; totalmente prohibido enviar informaci&oacute;n personal en el chat p&uacute;blico, si deseas enviar alg&uacute;n dato, siempre usa la mensajer&iacute;a privada, aun as&iacute; se recomienda&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px none; outline: 0px;">nunca enviar datos personales</strong>.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Est&aacute; totalmente prohibido enviar mensajes en relaci&oacute;n a la pedofilia, xenofob&iacute;a y cualquier otro mensaje que tenga que ver con el bullying, ciber-bullying o el acoso en general.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Est&aacute; totalmente prohibido solicitar fotograf&iacute;as a otros jugadores, independientemente del motivo que sea.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">El incumplimiento de la condici&oacute;n 10. Comunicaci&oacute;n del Servidor, conlleva una expulsi&oacute;n permanente de Amination Network.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="AcuerdoDeUsuario" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Acuerdo de Usuario</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Nos reservamos el derecho de cambiar, con o sin previo aviso, el precio de cualquier producto que se ha expuesto en la Tienda de Amination (http://donar.amination.es/). As&iacute; como cambiar el contenido de un rango espec&iacute;fico - los beneficios del producto se puede cambiar y usted no tendr&aacute; derecho a los antiguos beneficios si los cambiamos - Tenga en cuenta que, cualquier cambio que se realice en cuanto al beneficio de cualquier producto, no se realizar&aacute; sin una raz&oacute;n v&aacute;lida de cara al equilibrio del servidor.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">As&iacute; como tambi&eacute;n nos reservamos el derecho de retirar o eliminar cualquier producto comprado de la tienda (http://donar.amination.es/) con o sin previo aviso - esto siempre ser&aacute; por motivo explicable - principalmente suele ser por restablecer el servidor. En caso de eliminaci&oacute;n de modalidad, se dar&aacute; una indemnizaci&oacute;n por dicho motivo.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">En caso de presentar una demanda legal contra los empleados, propietarios, publicistas, ejecutivos, directores, socios y todas las partes relacionadas con el personal de este servidor, usted se compromete a indemnizar a cada una de las partes, ya sea relacionada con su compra o no.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Usted entiende y acepta que el uso de este sitio web y cualquier servicio o contenido proporcionado se hace disponible y le proporciona a su propio riesgo. Se le proporciona tal cual y renunciamos expresamente a todas las garant&iacute;as de ning&uacute;n tipo, tanto expresa como impl&iacute;cita, incluyendo, pero no limitando, a las garant&iacute;as de comerciabilidad, adecuaci&oacute;n para un prop&oacute;sito particular y no infracci&oacute;n. Usted entiende y acepta que ni nosotros ni ning&uacute;n participante en el servicio proporciona asesoramiento profesional de ning&uacute;n tipo y por lo tanto uso de asesoramiento o cualquier otra informaci&oacute;n es bajo su propio riesgo y sin nuestra responsabilidad de ning&uacute;n tipo. Algunas jurisdicciones no permiten la renuncia de garant&iacute;as impl&iacute;citas y la renuncia anterior puede no aplicarse a usted s&oacute;lo lo que se refiere a las garant&iacute;as impl&iacute;citas.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Usted entiende ya acepta expresamente que nosotros no seremos responsables de ning&uacute;n da&ntilde;o directo, indirecto, especial, incidental, consecuente o ejemplar, incluyendo pero no limitado a, da&ntilde;os por p&eacute;rdida de ganancias, buena voluntad, uso, datos u otras p&eacute;rdidas intangibles (incluso si se nos ha informado de la posibilidad de tales da&ntilde;os), resultantes de o que surjan de (I) El uso o la imposibilidad de utilizar el servicio, (II) El coste de obtener bienes y/o servicios derivados de cualquier transacci&oacute;n sustitutos introducidos en o a trav&eacute;s del servicio, (III) El acceso no autorizado o la alteraci&oacute;n de sus transmisiones de datos, (IV) Declaraciones o conducta de terceros en el servicio, o (V) cualquier otro asunto relacionado con el servicio. Tenga en cuenta que al aceptar los t&eacute;rminos del documento, tambi&eacute;n est&aacute; renunciando a su derecho. de tomar cualquier acci&oacute;n, legal o de otro tipo, contra cualquiera o cualquier cosa relacionada con el personal, la gesti&oacute;n, administradores, miembros, propietarios o cualquier host de este servidor. Usted reconoce, adem&aacute;s, que si alguna parte de este documento se encuentra para ser inv&aacute;lida o inaplicable en cualquier forma, las partes no se encuentra como no v&aacute;lidas o no aplicable, ser&aacute; considerada plenamente v&aacute;lida y vinculante.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Cualquier personal, los propietarios, los anfitriones, publicistas, ejecutivos, directores, empleados, socios y todas las partes relacionadas con el servidor, pueden excluirle del servidor permanentemente o temporalmente, sin posibilidad de reembolso &ndash; sin embargo, esto nunca ser&aacute; injustificada &ndash; esto solo sucede si rompe las reglas. Si obedece las reglas, nunca se le excluir&aacute; (banear&aacute;), as&iacute; de simple.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">El usuario tiene la obligaci&oacute;n de cumplimentar el formulario de compra con datos v&aacute;lidos, en caso de realizar compras con datos no v&aacute;lidos, ya sean inventados o falsos, se realizar&aacute; una denuncia a las autoridades pertinentes.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">La comunidad de Amination recoge tanto los &aacute;mbitos del servidor como del foro, de tal modo que si un jugador llegase a ser expulsado del foro, tambi&eacute;n se le podr&aacute; expulsar permanentemente de la network, as&iacute; como a todas las cuentas asociadas tanto en el foro como en el servidor.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los productos donados no son transferibles, ni entre usuarios ni modalidades, las donaciones se realizan a una modalidad y usuario en concreto.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Los productos obtenidos, as&iacute; como la cuenta de Amination Network no son vendibles fuera de Amination por moneda real ni por medio de ning&uacute;n m&eacute;todo de pago como por ejemplo Paypal.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">No se permite la compra/venta o el simple intercambio de cualquier contenido no relacionado con Amination o por art&iacute;culos, monedas o rangos de Amination Network, como por ejemplo: cuentas de otros juegos.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">En la solicitud del rango Helper, en casos excepcionales, seg&uacute;n el desarrollo que se observe del usuario, se podr&aacute; considerar prescindir del factor de edad m&iacute;nima para su caso.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Si un miembro del equipo staff procede a revisar la pantalla de un usuario baneado que realiz&oacute; su respectiva apelaci&oacute;n, y en dicho ordenador no se encuentran los logs asociados a su sanci&oacute;n por la que est&aacute; reclamando en .minecraft\logs, la apelaci&oacute;n quedar&aacute; rechazada directamente.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">La participaci&oacute;n en cualquier tipo de actividad con objetivo de desprestigiar cualquier aspecto del servidor, siempre que se considere que el usuario lo realiza mediante la desinformaci&oacute;n o falsa informaci&oacute;n que vayan m&aacute;s all&aacute; de cualquier tipo de cr&iacute;tica cuando se considere que se realiza realmente con intento de fastidiar de forma significativa a la comunidad en general, por lo que podr&aacute; ser sancionable tanto en el foro como en el servidor si se observan relaciones directas entre las diversas cuentas que participen en ello independientemente del medio empleado para realizar la difusi&oacute;n.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="PoliticaDeReemolso" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Pol&iacute;tica de Reembolso</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Todas las ventas realizadas son finales, no es posible realizarle el reembolso de ning&uacute;n producto bajo ninguna circunstancia. Si realiza cualquier acci&oacute;n para intentar conseguir el importe enviado a Amination puede causarle una exclusi&oacute;n del servidor / web. Nos reservamos el derecho de tomar cualquier acci&oacute;n legal o recaudaci&oacute;n necesaria para recuperar los da&ntilde;os en caso de una devoluci&oacute;n de cargo o &quot;charge-back&quot;.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p class="bold" id="Jurisdiccion" style="margin-top: 8px; margin-bottom: 8px; padding: 10px 0px; border: 0px none; outline: 0px; line-height: 16.5px; font-family: &quot;Open Sans&quot;; font-weight: 700; font-size: 15px; min-height: 1.25em; color: rgb(111, 111, 111); text-align: justify; ">Jurisdicci&oacute;n</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Todos los precios est&aacute;n reflejados en la web. No incluyen ning&uacute;n tipo de impuesto, se realizar&aacute; el pago en Euros o D&oacute;lares... dependiendo de su ubicaci&oacute;n. El precio pagado por el servicio le garantizar&aacute; el periodo establecido.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">Amination se reserva el derecho a modificar o a&ntilde;adir cualquier valor del impuesto tal como estipula la normativa Espa&ntilde;ola sin ning&uacute;n aviso.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">En caso de no respetar los T&eacute;rminos y Condiciones del servicio, Amination se reserva el derecho a suspender cualquier cuenta sin ning&uacute;n aviso ni su respectivo reembolso.</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>
<p style="margin-top: 8px; margin-bottom: 8px; padding: 0px; border: 0px none; outline: 0px; line-height: 16.5px; min-height: 1.25em; font-family: &quot;Open Sans&quot;; font-size: 15px; color: rgb(111, 111, 111); text-align: justify; ">&nbsp;</p>





</div>
</div>
</section>
</main>
<?php include("footer.php");?>
 <a id="top"><i class="fa fa-angle-up"></i></a>
<script type="text/javascript" src="assets/js/actions.js"></script>
</body>
</html>
